<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE papers [
<!ELEMENT menu (entry*)>
<!ELEMENT entry (text, subentry*)>
<!ATTLIST entry fileid CDATA #REQUIRED>
<!ELEMENT subentry (text)>
<!ATTLIST subentry fileid CDATA #REQUIRED>
<!ELEMENT text (#PCDATA)>
]>

<menu>
	<entry fileid="index">
		<text>Home</text>
	</entry>
	<entry fileid="aboutme">
		<text>About me</text>
	</entry>
	<entry fileid="papers">
		<text>Publications</text>
		<subentry fileid="$(shell $(RUN_XSLT) -im:list-file-ids data/menu.xml xsl/preview_menu.xsl)">
			<text>All</text>
		</subentry>
		<subentry fileid="papers_journal">
			<text>Journal articles</text>
		</subentry>
		<subentry fileid="papers_conf">
			<text>Conference proceedings</text>
		</subentry>
		<subentry fileid="papers_other">
			<text>Other publications</text>
		</subentry>
	</entry>
	<entry fileid="talks">
		<text>Presentations</text>
	</entry>
	<entry fileid="projects">
		<text>Projects</text>
	</entry>
</menu>
